<?php

namespace Programic\LaravelKubernetes\Formatter;

use Monolog\Formatter\JsonFormatter as JsonFormatterBase;

class JsonFormatter extends JsonFormatterBase
{
    public function __construct(
        int $batchMode = JsonFormatterBase::BATCH_MODE_JSON,
        bool $appendNewline = true,
        bool $ignoreEmptyContextAndExtra = false,
        bool $includeStacktraces = true)
    {
        parent::__construct($batchMode, $appendNewline, $ignoreEmptyContextAndExtra, $includeStacktraces);
    }

    protected function normalize(mixed $data, int $depth = 0): mixed
    {
        return parent::normalize($data, $depth); // TODO: Change the autogenerated stub
    }
}